# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee46b7b789f1916570d700fa3c472ceca358d8feff65e6417a28c163d5e0947c0c69294d999f0512efa93b95cc5f8c32d45b0baea8971742cb86fa607f8b38f3

test:
  secret_key_base: 7799534b131a3c757e6caa9fb871c161c286637a369c6edaf4253c68c52ddfd1d3a1ffd23ba2a3e35fd266a9bc3235c06ab8963089064c8f1f15b4f43643d87a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
